added docs
mia-care/SpringBoot-Mia-Care-Template pull request #1
Opened 2023-12-18 09:39 UTC by alexBonadei

2023-12-18 10:36 UTC, calairoh requested changes
PR LGTM
There is only a fix to do in the GitOps section regarding the way the template works for commint and branch automation

2023-12-18 10:36 UTC, calairoh commented on docs/20_Walkthrough.md
> +If the branch has been named correctly, the implementation task identifier is inserted automatically in the commit message. Therefore, when you run the command `git commit -m "message"`, the commit m
@alexBonadei Are you sure that the commit message insertion is performed by `jira-prepare-commit-msg`? As far as I know that library is for NodeJS.

2023-12-18 10:36 UTC, calairoh commented on docs/20_Walkthrough.md
> +Moreover, you can remove the automatic insertion of the implementation task identifier by removing the run of the `npx jira-prepare-commit-msg` command directly in the `./.husky/prepare-commit-msg` f
Same here. The way the commit is created is different from the one used in NodeJS template. I think this part has to be fixed.

2023-12-18 14:59 UTC, alexBonadei commented on docs/20_Walkthrough.md
> +If the branch has been named correctly, the implementation task identifier is inserted automatically in the commit message. Therefore, when you run the command `git commit -m "message"`, the commit m
Actually I implemented that script for the commit message insertion lol

2023-12-18 15:05 UTC, alexBonadei commented on docs/20_Walkthrough.md
> +Moreover, you can remove the automatic insertion of the implementation task identifier by removing the run of the `npx jira-prepare-commit-msg` command directly in the `./.husky/prepare-commit-msg` f
Yep

2024-02-09 10:55 UTC, calairoh approved these changes
LGTM

2024-02-09 10:56 UTC, merged